### ISSUE TITLE
Problems investigation by DB from Client

### ISSUE THREAD

**Issue by olga-jane** [olga-jane/prizm#1247]
Investigate DB to find out, what and where is wrong with some pipes. (DB is sent by mail)

a.	редактирование трубы № 2000-2015-002 и попытка записи результатов приводит к ошибке Prism 1.png
![image](https://cloud.githubusercontent.com/assets/8179067/6063558/dbd58e58-ad60-11e4-9c07-033552733a83.png)

b.	если выбрать Continue и ввести все 3 результата в состояние Passed и соответствующие результаты в нужных полях – деактивируются  кнопки Сохранить и Сохранить/Создать (Prism 2.png)
![image](https://cloud.githubusercontent.com/assets/8179067/6063587/f9466f48-ad60-11e4-9450-7601a870a020.png)
c.	после нескольких повторов действий из предыдущего пункта – вылетает программа полностью с диагностикой Prism 3.png
![image](https://cloud.githubusercontent.com/assets/8179067/6063596/0bf95470-ad61-11e4-9b34-79b5647e96d2.png)

**Comment by olga-jane** [comment]
2nd problem will be additionally corrected in future: деактивируются кнопки Сохранить и Сохранить/Создать (plate number cause) #1277

**Comment by DmitrySidorov** [comment]
part a) 
- the problem was caused by the inability to implement the convert to a data type of the results of measuring the length of the pipe and the ability to save the results of the inspection without data on the length measurement.

part b)
- the problem was caused by absence of data binding to control "plateNumber", because it lays on the inactive tab and have the property value "IsEditorActive" = "false" as a result of its empty data fields were copied to "PipeViewModel"

part c)
- the problem is not repeated. after changes according to the items listed above problem could not be reproduced (including on the basis of customer data). require additional research or a more detailed scenario.
