### ISSUE TITLE
save Joint without weld operation

### ISSUE THREAD

**Issue by DmitrySidorov** [olga-jane/prizm#877]
crash under save Joint without control operation or weld operation

Scenario:
1. Open "NewJoin"
2. Fill required fields
3. Chose the date of welding
4. Click Save or Save/New button
5. Select "No" in "Error" dialog
6. Click Save or Save/New button

Result:
An unhandled exception of type 'NHibernate.Exceptions.GenericADOException' occurred in NHibernate.dll
Additional information: could not execute batch command.[SQL: SQL not available]

**Comment by olga-jane** [comment]
gv.SetColumnError(controlDateGridColumn, Resources.VALUE_REQUIRED);
gv.SetColumnError(controlTypeGridColumn, Resources.VALUE_REQUIRED);
why date validation has been removed?

kapcia commented 18 hours ago
Because that was a check on null operation (type of control operation) and error was for null date.
In new commit ( for issue #902) i'll add check on date, inspectors\welders and result
